#!/bin/bash

# Configurable variables.
SOURCE="/path/to/ExpressionEngine/unzipped/folders/"

pre() {

	# Bail out without a version number
	if [ ! $1 ]; then
		echo >&2 "    Provide a version number."; exit 1
	fi

	# Check that the source directories are there..

	# Set variables
	EE_VERSION="$1"

	if [ ! $2 ]; then
		echo "    No system folder name given, assuming 'system'."
		SYSTEM="system"
	else
		SYSTEM="$2"
	fi

	# Copy install files.
	echo ":: Copying EE source files to current directory..."

	if [[  -d "$SOURCE/$EE_VERSION" ]]; then
		cp -r "$SOURCE/$EE_VERSION/"* ./
	else
		echo >&2 "ExpressionEngine source files not found. Check your SOURCE variable is pointing to the right place and that the version of ExpressionEngine exists there."; exit 2;
	fi


	# Remove crap
	echo ":: Remove default themes that won't be used..."
	rm -rf ./themes/site_themes/agile_records
	rm -rf ./themes/wiki_themes/
	rm -rf ./themes/cp_themes/corporate/
	rm -rf ./themes/profile_themes/agile_records/

	# Make public_html and move stuff around
	echo ":: Setting up a sane folder structure..."
	mkdir -p ./public_html/$SYSTEM
	mv ./system/expressionengine/templates ./
	mv ./system/expressionengine/third_party ./
	mv ./index.php ./public_html/
	mv ./themes ./public_html/
	mv ./images ./public_html/
	mv ./admin.php ./public_html/$SYSTEM/index.php

	# Add permissions script and run it
	echo ":: Enforce required permissions..."
	chmod -R o+w ./templates
	chmod -R o+w ./system/expressionengine/cache
	chmod 0666 ./system/expressionengine/config/config.php
	chmod 0666 ./system/expressionengine/config/database.php

	# Correct the index files to point correctly.
	echo ":: Set correct system folder path in indexes..."
	ruby -i -pe "gsub(/system_path\s+=\s+['\"]\.\/system['\"]/, 'system_path = \'../system\'')" ./public_html/index.php
	ruby -i -pe "gsub(/system_path\s+=\s+['\"]\.\/system['\"]/, 'system_path = \'../../system\'')" ./public_html/$SYSTEM/index.php

	# Give further instructions to the user
	echo "    Visit the control panel in your browser (at <base_url>/$SYSTEM/) and use the installer. Once done, run the post job."

}

post() {

	# Install master config.
	mkdir ./config
	curl -L https://github.com/focuslabllc/ee-master-config/raw/master/config/config.dev.php > ./config/config.dev.php
	curl -L https://github.com/focuslabllc/ee-master-config/raw/master/config/config.env.php > ./config/config.env.php
	curl -L https://github.com/focuslabllc/ee-master-config/raw/master/config/config.local.php > ./config/config.local.php
	curl -L https://github.com/focuslabllc/ee-master-config/raw/master/config/config.master.php > ./config/config.master.php
	curl -L https://github.com/focuslabllc/ee-master-config/raw/master/config/config.prod.php > ./config/config.prod.php
	curl -L https://github.com/focuslabllc/ee-master-config/raw/master/config/config.stage.php > ./config/config.stage.php
	curl -L https://github.com/focuslabllc/ee-master-config/raw/master/system/expressionengine/config/database.php > ./system/expressionengine/config/database.php
	curl -L https://gist.githubusercontent.com/EpocSquadron/c72a52ea51c272cf43bc/raw/9168ff2b93b6ee8ba6a02178b9648dae6afecc54/new_gist_file.php >> ./system/expressionengine/config/config.php

	# Make the htaccess
	echo ":: Generating the htaccess file."
	touch ./public_html/.htaccess

	## Add conditional auth snippet
	curl -L https://gist.github.com/raw/2636437/99d2cf0ee68256ff5c4a6abb5e1612b38d35c0db/.htaccess >>./public_html/.htaccess
	echo "" >>./public_html/.htaccess

	## Add EE index.php removing snippet
	curl -L https://gist.github.com/raw/5296158/688a88d093396dd316d96eed6571b220f04151ab/.htaccess >>./public_html/.htaccess
	echo "" >>./public_html/.htaccess

	## Add standard h5bp htaccess.
	curl -L https://github.com/h5bp/html5-boilerplate/raw/master/.htaccess >>./public_html/.htaccess
	echo "" >>./public_html/.htaccess


	# Remove installer
	echo ":: Removing installer directory..."
	rm -rf ./system/installer

	echo "Consider running `basename $0` laxify to set up Laxative, and `basename $0` gitify to initialize git properly."

}

gitify() {

	# Make the gitignore.
	echo "Generating gitignores..."
	curl -Lo .gitignore https://gist.github.com/raw/2936713/b22e6e3c97ad5504f45c5744ec1d98b3cc1c7b39/.gitignore
	curl -Lo system/expressionengine/cache/.gitignore https://gist.github.com/raw/2936703/d6b7ef32c8478a48c3994dcadc86837f4371184d/.gitignore

	cp -f system/expressionengine/cache/.gitignore public_html/images/**/_thumbs/

	if [ -d public_html/images/made ]; then
		cp -f system/expressionengine/cache/.gitignore public_html/images/made/
	fi

	if [ -d public_html/images/sized ]; then
		cp -f system/expressionengine/cache/.gitignore public_html/images/sized/
	fi

	if [ -d public_html/images/remote ]; then
		cp -f system/expressionengine/cache/.gitignore public_html/images/remote/
	fi

	# Start git
	echo "Setting up repository..."
	git init && git add . && git commit -m "Initial commit"

}

usage() {

  	read -r -d '' USAGE_TEXT <<HEREDOC
\033[1mUsage:\033[0m
	`basename $0` <command>

\033[1mDescription:\033[0m
	An opinionated tool for automating installs of ExpressionEngine from source zipballs.

\033[1mCommands:\033[0m
	\033[1mpre\033[0m - Run the pre-install process, which sets up the folder structure.
		\033[1mArguments:\033[0m pre <ee_version_number> [<system_folder_name>]
		<ee_version_number> - What version of EE to install. Must be present in the configured source directory.
		<system_folder_name> - Optional. What to name the system folder for url access. Note that this only changes the name of the system folder in public_html, not the name of the real system folder above root.

	\033[1mpost\033[0m - Run the post-install process, which should be done after the installer has been run from the browser.

	\033[1mlaxify\033[0m - Install laxative and run for the first time.

	\033[1mgitify\033[0m - Set git up in the current folder.

	\033[1mgitignorify\033[0m - Ensure all thumbnail and image cache directories are being gitignored. Run this when you've added new upload destinations, CE Image, or Image Sizer.

	\033[1mhelp\033[0m - Display this message.
HEREDOC

	echo -e "$USAGE_TEXT"
	exit 1

}

main() {

	# Bail out without an action.
	if [ ! $1 ]; then
		usage
	fi

	COMMAND=$1; shift

	case $COMMAND in
		"pre")
			pre $@
			;;
		"post")
			post $@
			;;
		"gitify")
			gitify $@
			;;
		"help")
			usage
			;;
	esac

}

main $@
